manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: caksoylar
      url-base: https://github.com/caksoylar
    - name: xudongz
      url-base: https://github.com/xudongzheng
    - name: urob
      url-base: https://github.com/urob
    - name: zephyr35
      url-base: https://github.com/petejohanson
  projects:
    - name: zmk
      remote: zephyr35 #zmkfirmware
      remote: zmkfirmware
#      revision: fix-battery-reporting
#      revision: custom-wq-pr
#      revision: core/zephyr-3.5-update
      revision: main
      import: app/west.yml
  self:
    path: config